### PR TITLE
feat: created farm-bot.sol, just has a withdraw method

### PR DESCRIPTION
**Pull request by cajubelt**
WIP need to test

trying to figure out how to write tests for this that use realistic Ubeswap LP tokens

### CODE REVIEW

**Comment by lisaqyli** [comment]
high level question:
Why do we need to import the whole ube-token contract dir? I thought we only need to interface with the LP token

**Comment by cajubelt** [comment]
I have now manually tested this so marking it as ready for review

It has unrelated ube contract stuff but yolo, it's a hackathon

**Comment by cajubelt** [comment]
@lisaqyli I was playing around with the UBE token contract trying to get a test running where a user obtains an ube token and deposits it into farmbot. I didn't get that far though. You'd need the full contract to get a token

**Comment by cajubelt** [comment]
closing this since #21 supercedes it

**Pull request closed without merging**
